# Copyright © 2026 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Danilo Gusicuma <danilo@lunarbase.ai>
#
# SPDX-License-Identifier: GPL-3.0-only

from pathlib import Path

from rdflib import RDF, URIRef

from lunar_api.flows.provenance.lunar_prov.parsers import load_execution_log, load_workflow
from lunar_api.flows.provenance.lunar_prov.mapping import build_prov_dataset
from lunar_api.flows.provenance.lunar_prov.prov_dataset import PROV


def _ctx(ds, iri: str):
    return ds.graph(URIRef(iri))


def test_bundles_and_base_uri_minting():
    wf_path = (
        Path(__file__).parent.parent / "examples" / "portfolio_allocation_flow.yaml"
    )
    lg_path = Path(__file__).parent.parent / "examples" / "reasoning_log.json"

    base = "http://lunarbase.ai/prov"
    wf = load_workflow(str(wf_path))
    log = load_execution_log(str(lg_path))
    ds, manifest = build_prov_dataset(
        wf, log, base_uri=base, embed_values=False, emit_redacted=True
    )

    b_pro = manifest["bundles"]["prospective"]
    b_ret = manifest["bundles"]["retrospective"]
    b_red = manifest["bundles"]["redacted"]

    assert b_pro.startswith(base)
    assert b_ret.startswith(base)
    assert b_red.startswith(base)

    g_pro = _ctx(ds, b_pro)
    g_ret = _ctx(ds, b_ret)
    g_red = _ctx(ds, b_red)

    # Each context is typed as prov:Bundle (in its own named graph)
    assert (URIRef(b_pro), RDF.type, PROV.Bundle) in g_pro
    assert (URIRef(b_ret), RDF.type, PROV.Bundle) in g_ret
    assert (URIRef(b_red), RDF.type, PROV.Bundle) in g_red


def test_prospective_depends_on_edges_inferred_from_step_refs():
    wf_path = (
        Path(__file__).parent.parent / "examples" / "portfolio_allocation_flow.yaml"
    )
    lg_path = Path(__file__).parent.parent / "examples" / "reasoning_log.json"

    base = "http://lunarbase.ai/prov"
    wf = load_workflow(str(wf_path))
    log = load_execution_log(str(lg_path))
    ds, manifest = build_prov_dataset(
        wf, log, base_uri=base, embed_values=False, emit_redacted=False
    )

    b_pro = manifest["bundles"]["prospective"]
    g_pro = _ctx(ds, b_pro)

    dependsOn = URIRef(base.rstrip("/") + "/dependsOn")

    def plan(sid):
        return URIRef(base.rstrip("/") + f"/plan/step/{sid}")

    # report depends on several upstream steps via $step references
    assert (plan("report"), dependsOn, plan("executive_summary_generator")) in g_pro
    assert (plan("report"), dependsOn, plan("portfolio_allocation_table")) in g_pro
    assert (plan("report"), dependsOn, plan("key_metrics_extractor")) in g_pro
    assert (plan("report"), dependsOn, plan("portfolio_allocation")) in g_pro


def test_retrospective_plan_linkage_and_used_generated_edges():
    wf_path = (
        Path(__file__).parent.parent / "examples" / "portfolio_allocation_flow.yaml"
    )
    lg_path = Path(__file__).parent.parent / "examples" / "reasoning_log.json"

    base = "http://lunarbase.ai/prov"
    wf = load_workflow(str(wf_path))
    log = load_execution_log(str(lg_path))
    ds, manifest = build_prov_dataset(
        wf, log, base_uri=base, embed_values=False, emit_redacted=False
    )

    b_pro = URIRef(manifest["bundles"]["prospective"])
    b_ret_iri = manifest["bundles"]["retrospective"]
    g_ret = _ctx(ds, b_ret_iri)

    # Find the report step activity
    # (we know the minted form from mapping.py)
    run_id = manifest["run_id"]
    act_report = URIRef(base.rstrip("/") + f"/run/{run_id}/activity/step/report")

    # It should have a plan mention entity linked back to the prospective bundle
    plan_mention = None
    for o in g_ret.objects(act_report, PROV.hadPlan):
        plan_mention = o
        break
    assert plan_mention is not None
    assert (plan_mention, PROV.asInBundle, b_pro) in g_ret
    assert (
        plan_mention,
        PROV.mentionOf,
        URIRef(base.rstrip("/") + "/plan/step/report"),
    ) in g_ret

    # It should use upstream step outputs (prov:used)
    out_exec = URIRef(
        base.rstrip("/") + f"/run/{run_id}/entity/output/executive_summary_generator"
    )
    out_table = URIRef(
        base.rstrip("/") + f"/run/{run_id}/entity/output/portfolio_allocation_table"
    )
    out_keys = URIRef(
        base.rstrip("/") + f"/run/{run_id}/entity/output/key_metrics_extractor"
    )

    assert (act_report, PROV.used, out_exec) in g_ret
    assert (act_report, PROV.used, out_table) in g_ret
    assert (act_report, PROV.used, out_keys) in g_ret

    # report output entity is generated by the report activity
    out_report = URIRef(base.rstrip("/") + f"/run/{run_id}/entity/output/report")
    assert (out_report, PROV.wasGeneratedBy, act_report) in g_ret


def test_llm_metadata_extraction_in_provenance():
    """Test that LLM nodes have generative flag, model, and token usage extracted."""
    wf_path = (
        Path(__file__).parent.parent / "examples" / "portfolio_allocation_flow.yaml"
    )
    lg_path = Path(__file__).parent.parent / "examples" / "reasoning_log.json"

    base = "http://lunarbase.ai/prov"
    wf = load_workflow(str(wf_path))
    log = load_execution_log(str(lg_path))
    ds, manifest = build_prov_dataset(
        wf, log, base_uri=base, embed_values=True, emit_redacted=False
    )

    b_ret_iri = manifest["bundles"]["retrospective"]
    g_ret = _ctx(ds, b_ret_iri)
    run_id = manifest["run_id"]

    # Define custom properties
    generativeProperty = URIRef(base.rstrip("/") + "/generative")
    modelProperty = URIRef(base.rstrip("/") + "/model")
    inputTokensProperty = URIRef(base.rstrip("/") + "/inputTokens")
    outputTokensProperty = URIRef(base.rstrip("/") + "/outputTokens")
    totalTokensProperty = URIRef(base.rstrip("/") + "/totalTokens")

    # Test LLM step: portfolio_allocation_input_formatter
    act_formatter = URIRef(
        base.rstrip("/")
        + f"/run/{run_id}/activity/step/portfolio_allocation_input_formatter"
    )

    # Check generative flag is True
    gen_values = list(g_ret.objects(act_formatter, generativeProperty))
    assert len(gen_values) > 0, "LLM step should have generative property"
    assert gen_values[0].toPython() is True, "LLM step generative flag should be True"  # type: ignore[attr-defined]

    # Check model is extracted
    model_values = list(g_ret.objects(act_formatter, modelProperty))
    assert len(model_values) > 0, "LLM step should have model property"
    assert "gpt-4" in str(model_values[0]), "Model should contain 'gpt-4'"

    # Check token usage is extracted
    input_token_values = list(g_ret.objects(act_formatter, inputTokensProperty))
    assert len(input_token_values) > 0, "LLM step should have input tokens"
    assert input_token_values[0].toPython() == 1589, "Input tokens should be 1589"  # type: ignore[attr-defined]

    output_token_values = list(g_ret.objects(act_formatter, outputTokensProperty))
    assert len(output_token_values) > 0, "LLM step should have output tokens"
    assert output_token_values[0].toPython() == 76, "Output tokens should be 76"  # type: ignore[attr-defined]

    total_token_values = list(g_ret.objects(act_formatter, totalTokensProperty))
    assert len(total_token_values) > 0, "LLM step should have total tokens"
    assert total_token_values[0].toPython() == 1665, "Total tokens should be 1665"  # type: ignore[attr-defined]

    # Test non-LLM step: get_cma_node (should have generative = False)
    act_cma = URIRef(base.rstrip("/") + f"/run/{run_id}/activity/step/get_cma_node")

    # Check generative flag is False
    gen_cma_values = list(g_ret.objects(act_cma, generativeProperty))
    assert len(gen_cma_values) > 0, "Non-LLM step should have generative property"
    assert (
        gen_cma_values[0].toPython() is False  # type: ignore[attr-defined]
    ), "Non-LLM step generative flag should be False"

    # Check no model property for non-LLM step
    model_cma_values = list(g_ret.objects(act_cma, modelProperty))
    assert len(model_cma_values) == 0, "Non-LLM step should not have model property"

    # Check no token usage for non-LLM step
    input_tokens_cma = list(g_ret.objects(act_cma, inputTokensProperty))
    assert len(input_tokens_cma) == 0, "Non-LLM step should not have input tokens"
