# SPDX-FileCopyrightText: Copyright © 2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Imen Ben Mahmoud <imen.benmahmoud@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only

from pathlib import Path
import argparse
from flask import Flask, jsonify, send_from_directory
from flask_cors import CORS

parser = argparse.ArgumentParser()
parser.add_argument("--graph_path", required=True, help="Path to the json graph file generated by the pipeline.")
args = parser.parse_args()


BASE_DIR = Path(__file__).resolve().parent
GRAPH_PATH = Path(args.graph_path).resolve()
JS_PATH = BASE_DIR / "visualization_stage_renderer.js"

app = Flask(__name__)
CORS(app)

@app.get("/")
def index():
    return send_from_directory(BASE_DIR, "index.html")

@app.get("/api/visualization")
def get_visualization():
    """API endpoint to get visualization data."""
    with open(JS_PATH, "r", encoding="utf-8") as f:
        js_code = f.read()
    with open(GRAPH_PATH, "r", encoding="utf-8") as f:
        tree_data = f.read()
    return jsonify({
        "javascript": js_code,
        "tree": tree_data
    })

if __name__ == "__main__":
    app.run(port=5000, debug=True, use_reloader=False)